### ISSUE TITLE
Get active orgs for add user dropdown

### ISSUE THREAD

**Issue by jay-meister** [postgres-plugin/people#7]
When we add a user, we can select an org to attach them to. At the moment we show all active orgs, unavailable orgs are 'grayed out'. This query should go some of the way toward solving that problem. 

```sql
SELECT
organisations.id AS org_id,
organisations.name AS org_name,
organisations.active AS org_active,
people.first_name AS person_first_name,
people.last_name AS person_last_name,
people.active AS person_active,
people.user_type AS person_user_type,
people.id AS person_id
FROM
organisations
-- We specifically want all organisations
LEFT OUTER JOIN
people
ON
people.org_id = organisations.id
WHERE
organisations.active = true
ORDER BY
people.id DESC
;
```

**Comment by mk4111** [comment]
Updating this issue, following the introduction of multiple primary users and secondary users ([see here](https://github.com/emfoundation/ce100-app/issues/560)):

We have an issue where organisations are repeated/duplicated because multiple users can be attached to it.

The .getActive query is used in /people/add and /people/{id}/edit; it seems we do not need to return `primary.id` anymore (although in edit-view we do need userId but this can be retrieved from the header instead). We need to update this query so that it just returns all active orgs.

This should simplify the query to:

```js
SELECT name, id,
FROM organisations
WHERE active = true
ORDER BY name ASC;
```

**Comment by mk4111** [comment]
@JMurphyWeb - does this sound okay to you?
